# Generated by Django 5.1.7 on 2025-03-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
